### ISSUE TITLE
WARN Unexpected response status from InfluxDB '400' - 'Bad Request' 

### ISSUE THREAD

**Issue by tw-bert** [fhussonnois/kafka-influxdb-reporter#1]
Hi Florian,

Great product, works (almost) straight out of the box.

We are getting a warning per measurement in kafka-server.log:

```
root@ubuntu-xenial:~/kafka-influxdb-reporter-master/dashboards# tail -f /var/log/kafka-server.log
[2017-05-24 11:20:32,541] WARN Unexpected response status from InfluxDB '400' - 'Bad Request' (com.github.fhuss.kafka.influxdb.InfluxDBClient)
[2017-05-24 11:20:42,541] WARN Unexpected response status from InfluxDB '400' - 'Bad Request' (com.github.fhuss.kafka.influxdb.InfluxDBClient)
```

At least some metrics work okay (like `Messages In Per Second`), so we'll ignore them for now:

![1](https://cloud.githubusercontent.com/assets/3413888/26401194/047591c8-4085-11e7-9141-11846bdcdb4f.png)

These measurements we can see:
```
InfluxDB shell version: 1.2.2
> use kafka
Using database kafka
> show measurements
name: measurements
name
----
BrokerTopicMetrics
ControllerStats
DelayedOperationPurgatory
GroupMetadataManager
JVM
KafkaController
KafkaRequestHandlerPool
KafkaServer
Log
LogCleaner
LogCleanerManager
Partition
Processor
ReplicaFetcherManager
ReplicaManager
RequestChannel
RequestMetrics
SessionExpireListener
SocketServer
Throttler
```

Build:
https://github.com/fhussonnois/kafka-influxdb-reporter 
master, 2c032c514be1a168c516c224d23b15264eb1c4c3

Environment:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)
OS name: "linux", version: "4.4.0-78-generic", arch: "amd64", family: "unix"
Default locale: en_US, platform encoding: UTF-8
InfluxDB version: 1.2.2
Telegraf version: 1.2.1
Kafka version: 2.12-0.10.2.1
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Apache Maven 3.3.9

Cheers, TW

**Comment by mrooding** [comment]
I have the same issue and it seems to be due to the following error:

`{"error":"field type conflict: input field \"value\" on measurement \"KafkaServer\" is type string, already exists as type float dropped=1"}`

I haven't been able to figure out yet why a value of type float would be inserted. All the requests I saw to Influx had had the correct string type.

**Comment by thspinto** [comment]
I think I might be because BrokerState is a float and ClusterId is a string.

This a part of the request that kafka-influxdb-reporter made to influxDB:
```
KafkaServer,brokerId=0,metric=BrokerState value=3,group="kafka.server" 1519080484558
KafkaServer,brokerId=0,metric=ClusterId value="rnpnW7OdQjiAo5WX2YS5BA",group="kafka.server" 1519080484558
KafkaServer,brokerId=0,metric=yammer-metrics-count value=1016,group="kafka.server" 1519080484558
```

The [influxdb docs](https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#field-type-discrepancies)  says that the this error wouldn't happen if the timestamps are in different shards, but I don't think it's a fix for this case.

**Comment by donaldleckie** [comment]
Concur with the ClusterId hypotheis, and while tracking it down also observed that there is POST body truncation due to a bug in InfluxDBClient when it uses the ByteBuffer. @tw-bert  in addition, I also had fun with the retention policies, and made a change to provide an empty value in config. This way the reporter's config will match my db.
I have a pull request which I'll drop in with all 3 fixes in it - hopefully @fhussonnois is happy to merge, or approve a merge so we can all benefit.

**Comment by donaldleckie** [comment]
actually - more digging suggests that https://github.com/Alcereo/kafka-influxdb-reporter has a reworking which resolves the ClusterId problem and truncated POST (because it uses the Influx client directly). Its worth giving that a go to see if it resolves your problems.

**Comment by donaldleckie** [comment]
@tw-bert  - dropped a pull request in from the head of my fork which has fixes for these updates. if you want to verify them, have a look at https://github.com/baldydonald/kafka-influxdb-reporter in the short term. Hopefully we'll be able to bring the changes back here and maintain a single line.

**Comment by fhussonnois** [comment]
Hi @baldydonald, thank you very much for you contibution. The PR LGTM. I think we can consider this issue resolved.
