### ISSUE TITLE
Is it possible to collect consumer metrics

### ISSUE THREAD

**Issue by simPod** [fhussonnois/kafka-influxdb-reporter#6]
And if so, how?

I mean these https://docs.confluent.io/current/kafka/monitoring.html#new-consumer-metrics

If I understand, this reporter now collects only `kafka.server` and consumer metrics require `kafka.consumer`.

Thanks!

**Comment by donaldleckie** [comment]
Hi Simon, I also wanted to solve this problem and looked into the confluent solution. I'm unsure exactly how confluent did it, but it would have to be measured outside the cluster - as you observe by a consumer metric.
Because we already have "canary" machines running consuming from the back of the kafka cluster which fed into our monitoring solution, we just used _its_ observed lag from the batches in our graphs. This pattern might be useful in solving your problem.
Cheers
Donald

**Comment by simPod** [comment]
@baldydonald thank you for response and the idea. If I find another solution for it, will share it. I'm not in hurry :)

**Comment by fhussonnois** [comment]
Hi @simPod, to monitor consumers you have to use another solution. Brokers are based on the library Dropwizard Metrics so it's easy to get a reporter. But consumers API uses this own metrics implementation. For example, you can use a JMX exporter like [Prometheus JMX Exporter](https://github.com/prometheus/jmx_exporter).

Confluent provides an interceptor implementation to monitore consumption lags ([javadoc](https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/ConsumerInterceptor.html))

kafka-influxdb-reporter can only be used to report metrics exposed from brokers

**Comment by simPod** [comment]
You're right, that's why I have to check these 
![image](https://user-images.githubusercontent.com/327717/49518881-00ff7e80-f8a0-11e8-9a2d-f96787d8201c.png)

when using https://github.com/yahoo/kafka-manager

Thanks!
